[env:esp32p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-p4-evboard
framework = arduino

board_build.mcu = esp32p4
board_build.f_cpu = 360000000L
board_build.flash_mode = dio

; Link your local backup files
board_build.partitions = rainbow.csv
board_build.cmake_extra_args = 
    -DSDKCONFIG_DEFAULTS=sdkconfig.defaults

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_MODE_OCT=1
    -DCONFIG_SPIRAM_SPEED_120M=1
    -DCONFIG_ESP_HOSTED_SDIO=1
    -DCONFIG_ESP32P4_REV_MIN_0_0=1

monitor_speed = 115200